name: flutter_restaurant_menu_app
description: A Flutter application for restaurant menu management with admin and customer interfaces.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  
  # Data Management
  shared_preferences: ^2.1.2
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  sqflite_common_ffi: ^2.3.2 
  path_provider_android: ^2.2.0
  
  # Networking
  http: ^0.13.6
  connectivity_plus: ^4.0.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^3.0.7
  logger: ^1.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  # Temporarily commenting out assets until they are available
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/translations/
    
  # Temporarily commenting out fonts until they are available
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
