name: flutter_restaurant_menu_app
description: A Flutter application for restaurant menu management with admin and customer interfaces
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.5
  shared_preferences: ^2.1.0
  path: ^1.8.2
  uuid: ^3.0.7
  intl: ^0.18.0
  path_provider: ^2.0.14
  image_picker: ^1.0.4  # Updated to a stable version
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
